version: '3.1'

secrets:
  db_ini:
    file: 'images/omeka_classic/db.ini'
  mysql_env:
    file: 'images/omeka_db/.env'

services:
  db:
    image: 'omeka_db:latest'
    volumes:
      - 'db:/var/lib/mysql'
    secrets:
      - mysql_env
  omeka_app:
    image: 'omeka_classic:latest'
    ports:
      - '80:80'
    volumes:
      - 'files:/var/www/html/files'
    secrets:
      - db_ini

volumes:
  db:
  files:
