version: '2'

services:
  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.6'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  omeka_app:
    restart: 'unless-stopped'
    image: 'omeka_classic:latest'
    ports:
      - '80:80'
    links:
      - 'db'
    volumes:
      - 'files:/var/www/html/files'
      - 'plugins:/var/www/html/plugins'

volumes:
  db:
  files:
  plugins:
