version: '3.1'

secrets:
  db_ini:
    file: 'images/omeka_classic/db.ini'
  omeka_db_password:
    external: true
  omeka_db_root_password:
    external: true

services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_DATABASE: omeka
      MYSQL_PASSWORD_FILE: /run/secrets/omeka_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/omeka_db_root_password
      MYSQL_USER: omeka
    volumes:
      - 'db:/var/lib/mysql'
    secrets:
      - omeka_db_password
      - omeka_db_root_password
  omeka_app:
    image: 'quay.io/upennlibraries/omeka_classic:latest'
    ports:
      - '80:80'
    volumes:
      - 'files:/var/www/html/files'
    secrets:
      - source: db_ini
        target: /var/www/html/db.ini

volumes:
  db:
  files:
